[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meine_lib"
version = "0.1.0"
dependencies = [
  "requests>=2.28.0",
  "configargparse>=1.5.3"
]
