name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  # Detect_Project_Changes:
  #   name: Check for new version
  #   runs-on: ubuntu-latest
  #   outputs:
  #     changed: ${{ steps.check.outputs.changed }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Check if pyproject.toml changed
  #       id: check
  #       run: |
  #         if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^pyproject\.toml$'; then
  #           echo "changed=true" >> $GITHUB_OUTPUT
  #         else
  #           echo "changed=false" >> $GITHUB_OUTPUT
  #         fi

  build-and-publish:
    name: Publish PyPI Package
    # if: github.ref == 'refs/heads/main' && needs.Detect_Project_Changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    # needs: [Detect_Project_Changes]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
        # uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
